export const NavigatorName = {
    Welcome: 'Welcome',
    Main: 'Main',
    ChatPrivate: 'ChatPrivate',
    ChatGroup: 'ChatGroup',
    Contact: 'Contact',
    Setting: 'Setting',
    EditMyInfoing: 'EditMyInfoing',
    UserManagement: 'UserManagement',
    Login: 'Login',
    Register: 'Register',
    EditTextInfo: 'EditTextInfo',
    AddFriend: 'AddFriend',
    FindAddFriend: 'FindAddFriend',
    FindAddGroup: 'FindAddGroup',
    ChooseChatGroup: 'ChooseChatGroup',
    EditMyInfo: 'EditMyInfo',
    CreateChatGroup: 'CreateChatGroup',
    GroupInfo: 'GroupInfo',
    FriendChatSetting: 'FriendChatSetting',
    FriendInfo: 'FriendInfo'
}